### ISSUE TITLE
Axt, Messer und ohne Shot kill geht nicht

### ISSUE THREAD

**Issue by DJJayT** [KWStudios/RageMode#5]
Hallo, bei uns auf dem Server geht die Axt, das Messer und (wenn du das eingestellt hast) der One Shot Bogen kill wie auf Gomme nicht.

MFG DJJayT

**Comment by koraykoska** [comment]
Hi, könntest du bitte näher erklären was genau nicht funktioniert? Am besten wäre auch wenn du uns deinen Konsolen Log schicken könntest damit wir die Fehler auslesen können.

Außerdem wäre es super wenn du Screenshots oder ein Video von dem Fehler machen könntest dann können wir dir weiterhelfen.

**Comment by JayTalge** [comment]
https://youtu.be/3Zay6-E4lNg (NICHT BEARBEITET! Gerade keine Zeit!)

In der Konsole steht nichts

**Comment by koraykoska** [comment]
OK das sieht sehr nach Inkompatibilität mit einem anderen Plugin aus. Könntest du uns eine Pluginliste zusammenstellen, dann können wir testen woran es liegt.

Außerdem müssen nicht unbedingt Fehler in der Konsole stehten, es könnte trotzdem unter Umständen hilfreich sein also wenn es dir nichts ausmacht schick uns bitte trotzdem den Log direkt nach einem kurzen Spiel.

**Comment by JayTalge** [comment]
Sorry fürs nicht mehr antworten, aufgrund der Dauer schließe ich das Problem einfach
